language: java
install: true

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - chmod +x gradlew

stages:
  - name: build
  - name: snapshot
    if: branch = master
  - name: release
    if: branch = release

jobs:
  include:
    - stage: build
      script: ./gradlew build
    - stage: release
      script: ./gradlew bintrayUpload -x test -P bintrayUser=$BINTRAY_USER -P bintrayApiKey=$BINTRAY_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER